

discard """
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, find the sum of the even-valued terms.
"""

# generate fibonacci sequence with even numbers only
# where values of terms dont exceed 4000000
iterator fib(): int =
  var
    a = 0
    b = 1
  var tmp:int

  while b < 4000000:
    tmp = b
    b += a
    a = tmp
    if b mod 2 == 0:
      yield b


var sum = 0
for i in fib():
  sum += i

echo($sum)
